### ISSUE TITLE
Sprint set as false but still grows things

### ISSUE THREAD

**Issue by Zelarian** [Funwayguy/TS2K16#2]
I don't know where to ask this. I went into the ts2k16.cfg file and set the sprint to false:
    # Allows users to sprint instead of sneaking [default: true]
    B:"Allow Sprinting"=false

But things still grow when I run past. It is also growing grass even though grass is listed under the blacklist. The only other thing I changed was making "All Plants" true, so it would work on my crops. Am I doing anything wrong? How do I fix this?

I am playing minecraft 1.11.2
The mod version is TS2K16-1.1.4.jar

This is the config file.
# Configuration file

general {
    # Make growth effect all plants, not just saplings [default: false]
    B:"All Plants"=true

    # Allows users to sprint instead of sneaking [default: true]
    B:"Allow Sprinting"=false

    # Plants blacklisted from the effect (Case Sensitive) [default: [minecraft:grass]]
    S:Blacklist <
        minecraft:grass
     >

    # Percent chance that growth will occur [range: 1 ~ 100, default: 25]
    I:Chance=25

    # Minimum number of ticks between each growth [range: 0 ~ 2147483647, default: 10]
    I:Cooldown=10

    # Growth effect radius around the player [range: 1 ~ 16, default: 3]
    I:Radius=3

    # Additional plants that can be affected (Case Sensitive) [default: ]
    S:Whitelist <
     >
}

Thankyou.

**Comment by NiSiSuinegEht** [comment]
I'd like to chime in by saying that I'm experiencing the same thing.  Using modpack "The Simple Life 2" updated to current as of this posting.  

I just looked into your code, and proposed a change to fix this.  I've never used github for this kind of thing before, so I hope I did it right.

**Comment by Funwayguy** [comment]
Not really sure how I missed that check but I'll push out an update soon to fix it. I'm moving the additional check to a slightly different position than your PR though (I get really picky about my code) and also porting it across to the other 2 versions.

**Comment by Zelarian** [comment]
Thank you :)

**Comment by Funwayguy** [comment]
New versions uploaded to CurseForge. Also finally updated the repository with current code from all versions

**Comment by NiSiSuinegEht** [comment]
Awesome!
