### ISSUE TITLE
mod support

### ISSUE THREAD

**Issue by RealLith** [Funwayguy/TS2K16#4]
It seems the white-list and blacklist for 1.12 is either broken or im doing something wrong or... idk hwta els could be.

I added biomeoplenty sapling to the white-list "biomesoplenty:sapling_0:3" and it isint working.
Then i tried more stuff like adding the ore dic and even tried botania petals (they work with bonemeal and the mod description say it works with anything that can be bone mealed and u add to the white-list).
      "biomesoplenty:sapling_0:3
        ore:treeSapling
        ore:blockSlimeGrass
        botania:buriedpetals:0"

Yes none of that plants work. I even removed the "minecraft:grass" from the blacklist and it still dosent get bone mealed.

Vanilla saplings work fine - modded none. even harvestcraft saplings arent working.

im using the latest curse version: 1.2.8

if I change B:"All Plants" to true then every sapling (and grass block) even from mods work fine so I have no clue whats going on.
here is the entire config file:

# Configuration file

general {
    # Make growth effect all plants, not just saplings [default: false]
    B:"All Plants"=false

    # Allows users to sprint instead of sneaking [default: true]
    B:"Allow Sprinting"=true

    # Plants blacklisted from the effect (Case Sensitive) [default: [minecraft:grass]]
    S:Blacklist <
        
     >

    # Percent chance that growth will occur [range: 1 ~ 100, default: 25]
    I:Chance=100

    # Minimum number of ticks between each growth [range: 0 ~ 2147483647, default: 10]
    I:Cooldown=5

    # Growth effect radius around the player [range: 1 ~ 16, default: 3]
    I:Radius=5

    # Additional plants that can be affected (Case Sensitive) [default: ]
    S:Whitelist <
        biomesoplenty:sapling_0:3
        ore:treeSapling
        ore:blockSlimeGrass
        botania:buriedpetals:0
     >
}

**Comment by RealLith** [comment]
In addiction, i tried putting "B:"Allow Sprinting"=true" and blacklisting few saplings and blocks so they wouldn't get effected. It still didint work - all plants, including the ones i blacklisted, would get affected.

My guess would be that white-list and blacklist does not work with modded stuff.

putting "B:"Allow Sprinting"=false" and putting vanilla grass block to the blacklist works fine and removing it works fine so it sounds like this mod no longer supports modded stuff.

**Comment by Funwayguy** [comment]
Forgot to test this today, was too caught up in finishing a Better Questing update. I'll see what I can do tomorrow about this.

The mod is itended to work with modded blocks so this might be a bug.

**Comment by RealLith** [comment]
Just to make it clearer (if I havent since english isint my main language) it does work with modded blocks IF you set "B:"All Plants"=true" BUT then you CANT blacklist.

ALSO, in addition, if you have "B:"All Plants"=false" and whitelist modded plants/saplings, they wont work.

My guess is that the whitelist/blacklist isint working properly.
Since if you have "B:"All Plants"=true" it does work with modded plants I guess it works fine with modded. But if you whitelist those plants and set "B:"All Plants"=false" it dosent work.
idk im not a coder/dev. I just wanted to make sure i made it clear as possible to not create any misunderstandings.

**Comment by Funwayguy** [comment]
Looked though the code today and it makes me want to facepalm a little. The actual issue is that Twerk Sim doesn't actually support metadata or ore dictionary names... yea I know, stupid oversight on my part. Going to have to rewrite the config system a bit to fix that.

(will likely just recycle the system Ore Excavation uses and call it a day)

**Comment by Funwayguy** [comment]
In case you missed it, I sent out an update which should fix this. Should also be a lot more flexible in what you throw at it in the config. The only remaining blocks that would be unsupported would be ones not using the standard bonemeal interaction hooks.

Note: For ore dictionary entries just use the name without any prefix.
