### ISSUE TITLE
[Suggestion] Dimension whitelist, or gamestage integration

### ISSUE THREAD

**Issue by CritFlaw** [Funwayguy/TS2K16#7]
I'm working on a skyblock & overworld modpack, and would love to be able to limit the mod to a stage or a dimension, so that it's only available in the skyblock. This would be a very useful feature in general, the same way ore excavate can be earned, so could this.

**Comment by Funwayguy** [comment]
I've added Game Stage support into version 1.2.10

**Comment by CritFlaw** [comment]
That's awesome! Thanks!

**Comment by CritFlaw** [comment]
One question though, how will it integrate exactly, since there's no documentation on the method? Is it going to be a config option or using zenscript?

**Comment by CritFlaw** [comment]
Just saw the config update. Thank you again.

**Comment by Funwayguy** [comment]
It's just a simple config entry with the stage name. No fancy scripts. I also made it so it's not per-block to keep complexity down.
